.TH ISOTEST 1 "Mar 2017" "Version 1.0"
.SH NAME
isotest \- Test ISO filesystem reader
.SH SYNOPSIS
.B isotest

.SH DESCRIPTION
.B isotest
is used to test the ISO filesystem reader.
It is a functional duplicate of fs_iso9660, but designed to run on a PC for
testing.
In Linux, accessing the /dev device on a single-session CD puts the
"bootstrap" zone at offset 0x8000, and the begin of the CD data itself at

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by Dan Potter in 2000.
