.TH SCRAMBLE 1 "Mar 2017" "Version 1.0"
.SH NAME
scramble \- scramble a Dreamcast executable
.SH SYNOPSIS
.B scramble
[
.B \-d
]
.IR from
.IR to

.SH DESCRIPTION
.B scramble
is used to rearrange the contents of an executable in order for it
to be readable by the SEGA Dreamcast game console when using CDs.
This circumvents the encryption measures by SEGA to disallow homebrew.
.SH OPTIONS
.TP
.BI -d
Reverse the process, i.e. descramble.

.SH EXAMPLES

.EX
.B
   scramble executable.elf executable_scrambled.elf
.EE

.EX
.B
   scramble -d executable_scrambled.elf executable.elf
.EE

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by Marcus Comstedt and was obtained from
his site (http://mc.pp.se/dc/).
