.TH GENTEXFONT 1 "Mar 2017" "Version 1.0"
.SH NAME
gentexfont \- Create TXF font from X11 fonts
.SH SYNOPSIS
\fBgentexfont\fR [\fIOPTION\fR]... [\fIFILE\fR]...
[
.B \-d
]
.IR from
.IR to

.SH DESCRIPTION
.B gentexfont
is used to create TXF font files from X11 fonts.
Dan Potter downloaded this from a web article which discusses TXF fonts.

.SH OPTIONS
.TP
.BR \-w
Specify texture width. Defaults to 256.

.TP
.BR \-h "
Specify texture height. Defaults to 256.

.TP
.BR \-gap
Specify gap between glyphs. Defaults to 1. 

.TP
.BR \-byte
Use a byte encoding (less compact)

.TP
.BR \-bitmap
Use a bitmap encoding (default).

.TP
.BR \-glist
Specify glyph list, e.g. "abcdef"

.TP
.BR \-fn
Specify X11 font name. Defaults to Adobe Courier.

.TP
.BR \-file
Specify output file name. Defaults to default.txf.

.SH EXAMPLES

.EX
.B
   gentexfont executable.elf executable_gentexfontd.elf
.EE

.EX
.B
   gentexfont -d executable_gentexfontd.elf executable.elf
.EE

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by Marcus Comstedt and was obtained from
his site (http://mc.pp.se/dc/).
