.TH KMGENC 1 "Mar 2017" "Version 1.0"
.SH NAME
kmgenc \- Store images as SEGA Dreamcast PVR textures in a KMG container
.SH SYNOPSIS
\fBkmgenc\fR [\fIOPTION\fR]... [\fIFILE\fR]...

.SH DESCRIPTION
.B kmgenc
is used to convert images to the SEGA Dreamcast's available
image formats. Typically this means RGB565, ARGB1555 or ARGB4444.

.SH OPTIONS
.TP
.BR \-v ", " \-\-verbose\fR
Print more information during processing.

.TP
.BR \-d ", " \-\-debug\fR
Print much more information.

.TP
.BR \-a4 ", " \-\-argb4444\fR
Use 4 bit alpha channel (Dreamcast PVR texture format ARGB4444).

.TP
.BR \-a1 ", " \-\-argb1555\fR
Use 1 bit alpha channel (Dreamcast PVR texture format ARGB1555).

.SH EXAMPLES

.EX
.B
   kmgenc -a image.png
.EE

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by Gil Megidish in 2002 and modified by
Dan Potter in 2003.

.SH BUGS
kmgenc is very incomplete and you may want to use vqenc instead, since it is also
capable of outputting kmg container files with mipmaps and VQ compression.
