.TH WAV2ADPCM 1 "Mar 2017" "Version 1.0"
.SH NAME
wav2adpcm \- Convert between WAV and ADPCM audio data
.SH SYNOPSIS
.B wav2adpcm
.B \-t
.B \-f
.IR from.wav
.IR to.wav

.SH DESCRIPTION
.B wav2adpcm
is used to convert WAV audio data to the ADPCM format supported by the
hardware of the SEGA Dreamcast game console.
.SH OPTIONS
.TP
.BI -t
Convert from WAV to ADPCM
.BI -f
Convert from ADPCM to WAV

.SH EXAMPLES

.EX
.B
   wav2adpcm -t from.wav to_adpcm.wav
.EE

.EX
.B
   wav2adpcm -f from_adpcm.wav to.wav
.EE

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by BERO <bero@geocities.co.jp> and modified by Dan Potter.
