.TH RDTEST 1 "Mar 2017" "Version 1.0"
.SH NAME
rdtest \- Test romdisk filesystem reader
.SH SYNOPSIS
.B rdtest

.SH DESCRIPTION
.B rdtest
is used to test the romdisk filesystem reader.
It is a functional duplicate of fs_romdisk, but designed to run on a PC for
testing.
Loads to VMA 0x8c010000. This is an exact functional duplicate of the routine
in process/elf.c and is used for testing new changes first.

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by Dan Potter in 2001.
