.TH DCBUMPGEN 1 "Mar 2017" "Version 1.0"
.SH NAME
dcbumpgen \- dcbumpgen a Dreamcast executable
.SH SYNOPSIS
.B dcbumpgen
.IR from
.IR to

.SH DESCRIPTION
.B dcbumpgen
is used to generate SEGA Dreamcast PVR bumpmap textures.

.SH EXAMPLES

.EX
.B
   dcbumpgen infile.png outfile.raw
.EE

.EX
.B
   dcbumpgen infile.jpg outfile.raw
.EE

.SH AUTHOR
This manual page was initially written by Stefan Galowicz <bogglez@protonmail.ch>,
for the KOS project.
.TP
The program has been initially written by Frederik Ehnbom in 2005.
